### PR TITLE
New files for Mac startup app

### PR DESCRIPTION
**Pull request by thomshaw92**
The app is a DMG to go on the website @stebo85 @aswinnarayanan 
Needs testing @meganEJcampbell

### CODE REVIEW

**Comment by thomshaw92** [comment]
@stebo85 can you please move the files [start-neurodesktop-mac.dmg](https://github.com/NeuroDesk/neurodesktop/blob/main/MacOs_run_Neurodesk/Start_NeuroDesktop_script_files/start-neurodesktop-mac.dmg) and README.md up one level to make it consistent with the Linux and Windows folders?

**Comment by stebo85** [comment]
done, can you check @thomshaw92 ?

**Comment by meganEJcampbell** [comment]
I couldn't get it to work: screenshots for what it looks like, including step of needed to go to systems preferences and allow it under Security settings (requires admin rights to allow). Final issue: The action 'Run Shell Script' encountered an error: xcrun error... (see last image)


Screenshot 2022-12-07 at 5 19 21 pm
Screenshot 2022-12-07 at 5 19 31 pm
Screenshot 2022-12-07 at 5 19 55 pm
Screenshot 2022-12-07 at 5 20 10 pm
Screenshot 2022-12-07 at 5 20 34 pm

**Comment by meganEJcampbell** [comment]
Sorry meant to give system info: 
Macbook pro, 2020 2Ghz quad intel i5, macOS Ventura 13.0.1



> I couldn't get it to work: screenshots for what it looks like, including step of needed to go to systems preferences and allow it under Security settings (requires admin rights to allow). Final issue: The action 'Run Shell Script' encountered an error: xcrun error... (see last image)
> 
> Screenshot 2022-12-07 at 5 19 21 pm Screenshot 2022-12-07 at 5 19 31 pm Screenshot 2022-12-07 at 5 19 55 pm Screenshot 2022-12-07 at 5 20 10 pm Screenshot 2022-12-07 at 5 20 34 pm

**Pull request merged**
